vpc:
  domain: 301
  peer_gateway: true
  pkl_vrf: management
  port_channel: Port-Channel301
  port_channels:
    - name: 301
      members:
        - member: Ethernet1/7
          mode: active
        - member: Ethernet1/6
          mode: active
  features:
    - lacp
    - vpc
  l1_members:
    - name: Ethernet1/6
      mode: layer2
      enabled: true
    - name: Ethernet1/7
      mode: layer2
      enabled: true
  members:
    - name: Ethernet1/6
      mode: trunk
    - name: Ethernet1/7
      mode: trunk
svi:
  vlans:
    - name: V3301_P2P-SITE3-CPE1-CPE2
      vlan_id: 3301

l3_features:
  - interface-vlan
  - bfd
  - ospf
  - bgp

vlan_hosts:
  - enabled: true
    mode: ce
    state: active
    vlan_id: 3402
    name: V3402_TEST_BCG
    mapped_vni: 4003402
    route_distinguisher: auto
    route_target_export:
      - 65002:100
    route_target_import:
      - 65001:100
      - 65000:100