vpc:
  domain: 201
  peer_gateway: true
  pkl_vrf: management
  port_channel: Port-Channel201
  port_channels:
    - name: 201
      members:
        - member: Ethernet1/7
          mode: active
        - member: Ethernet1/6
          mode: active
  features:
    - lacp
    - vpc
  l1_members:
    - name: Ethernet1/6
      mode: layer2
      enabled: true
    - name: Ethernet1/7
      mode: layer2
      enabled: true
  members:
    - name: Ethernet1/6
      mode: trunk
    - name: Ethernet1/7
      mode: trunk
svi:
  vlans:
    - name: V3201_P2P-SITE2-CPE1-CPE2
      vlan_id: 3201

l3_features:
  - interface-vlan
  - bfd
  - ospf
  - bgp
  - pim
  - vn-segment-vlan-based
  - nv overlay
  - fabric forwarding

vlan_hosts:
  - enabled: true
    mode: ce
    state: active
    vlan_id: 3402
    name: V3402_TEST_BCG
    mapped_vni: 4003402
evni:
  - vni: 4003402
    route_distinguisher: auto
    route_target_export: auto
    route_target_import: auto
    multicast_group: 239.192.22.2
    interface: nve1
    assoc_vrf: false