vpc:
  domain: 201
  peer_gateway: true
  pkl_vrf: management
  port_channel: Port-Channel201
  port_channels:
    - name: 201
      members:
        - member: Ethernet1/7
          mode: active
        - member: Ethernet1/6
          mode: active
  features:
    - lacp
    - vpc
  l1_members:
    - name: Ethernet1/6
      mode: layer2
      enabled: true
    - name: Ethernet1/7
      mode: layer2
      enabled: true
  members:
    - name: Ethernet1/6
      mode: trunk
    - name: Ethernet1/7
      mode: trunk
svi:
  vlans:
    - name: V3201_P2P-SITE2-CPE1-CPE2
      vlan_id: 3201

l3_features:
  - interface-vlan
  - bfd
  - ospf