---
- name: Configure BGP IPv4 CPE
  hosts: cpe
  tasks:
    - name: Enable features
      cisco.nxos.nxos_feature:
        feature: "{{ item }}"
        state: enabled
      loop: "{{ l3_features }}"

    - name: Enable overlay
      cisco.nxos.nxos_evpn_global:
        nv_overlay_evpn: true

    - name: Configure BGP Template & Process
      cisco.nxos.nxos_bgp_templates:
        config: "{{ l3.bgp_templates }}"

    - name: Configure BGP on VRF
      cisco.nxos.nxos_bgp_global:
        config: "{{ l3.bgp }}"

    - name: Save configuration
      cisco.nxos.nxos_config:
        save_when: always
