---
- name: Configure L3 Interface
  hosts: isn,cpe
  tasks:
    - name: Configure VRF
      cisco.nxos.nxos_vrf:
        name: "{{ vrf.name }}"
        state: present
      when: inventory_hostname in groups['isn']

    - name: Enable features
      cisco.nxos.nxos_feature:
        feature: "{{ item }}"
        state: enabled
      loop: "{{ l3_features }}"

    - name: Create vlan
      cisco.nxos.nxos_vlans:
        config: "{{ svi.vlans }}"

    - name: Configure L3 Interface
      cisco.nxos.interfaces:
        config: "{{ l3.members }}"
        state: merged
    
    - name: Assign interfaces to VRF
      cisco.nxos.nxos_vrf_interface:
        interface: "{{ item.name }}"
        vrf: "{{ vrf.name }}"
        state: present
      loop: "{{ l3.members }}"
      when: inventory_hostname in groups['isn']

    - name: Assign IP to interface
      cisco.nxos.nxos_l3_interfaces:
        config: "{{ l3.l3_members }}"
        state: merged
    
    - name: Configure OSPF Process
      cisco.nxos.nxos_ospfv2:
        config: "{{ ospf }}"
        state: merged

    - name: Configure OSPF Interface
      cisco.nxos.nxos_ospf_interfaces:
        config: "{{ l3.ospf_members }}"
        state: merged

    - name: Save configuration
      cisco.nxos.nxos_config:
        save_when: always