---
- name: Configure PIM
  hosts: all
  tasks:
    - name: Enable features
      cisco.nxos.nxos_feature:
        feature: "{{ item }}"
        state: enabled
      loop: "{{ l3_features }}"

    - name: Configure PIM Interfaces
      cisco.nxos.nxos_pim_interface:
        hello_interval: "{{ item.hello_interval }}"
        hello_interval_ms: "{{ item.hello_interval_ms }}"
        interface: "{{ item.interface }}"
        sparse: "{{ item.sparse }}"
        state: present
      loop: "{{ l3.pim_interfaces }}"

    - name: Enable BFD on all Interfaces
      cisco.nxos.nxos_pim:
        bfd: true

    - name: Configure RP Address
      cisco.nxos.nxos_pim_rp_address:
        bidir: "{{ item.bidir }}"
        group_list: "{{ item.group_list }}"
        rp_address: "{{ item.rp_address }}"
        state: present
      loop: "{{ pim }}"