---
- name: Enable VXLAN
  hosts: cpe
  tasks:
    - name: Configure VLAN Mapped to VNI
      cisco.nxos.nxos_vlans:
        config: "{{ vlan_hosts }}"
    
    - name: Configure EVPN
      cisco.nxos.nxos_evpn_vni:
        vni: "{{ item.vni }}"
        route_distinguisher: "{{ item.route_distinguisher }}"
        route_target_import: "{{ item.route_target_import }}"
        route_target_export: "{{ item.route_target_export }}"
        state: present
      loop: "{{ evni }}"

    - name: Configure VTEP Interface
      cisco.nxos.nxos_vxlan_vtep: "{{ vxlan_vtep_interface }}"

    - name: Configure VTEP VNI
      cisco.nxos.nxos_vxlan_vtep_vni:
        interface: "{{ item.interface }}"
        vni: "{{ item.vni }}"
        multicast_group: "{{ item.multicast_group }}"
      loop: "{{ evni }}"

    - name: Save configuration
      cisco.nxos.nxos_config:
        save_when: always