---
- name: Enable VXLAN
  hosts: cpe
  tasks:
    - name: Enable features
      cisco.nxos.nxos_feature:
        feature: "{{ item }}"
        state: enabled
      loop: "{{ vxlan_features }}"

    - name: Enable overlay
      cisco.nxos.nxos_evpn_global:
        nv_overlay_evpn: true

    - name: Configure VLAN Mapped to VNI
      cisco.nxos.nxos_vlans:
        config: "{{ vlan_hosts }}"
    
    - name: Configure EVPN
      cisco.nxos.nxos_evpn_vni:
        vni: "{{ item.member_vni }}"
        route_distinguisher: "{{ item.route_distinguisher }}"
        route_target_import: "{{ item.route_target_import }}"
        route_target_export: "{{ item.route_target_export }}"
        state: present
      loop: "{{ vlan_hosts }}"

    - name: Configure VTEP Interface
      cisco.nxos.nxos_vxlan_vtep: "{{ vxlan_vtep_interface }}"

    #- name: Save configuration
    #  cisco.nxos.nxos_config:
    #    save_when: always