ansible_host: 10.190.30.13
vpc_device:
  pkl_dest: 10.190.30.12
  pkl_src: 10.190.30.13
  role_priority: 32768

lab:
  disable:
    - enabled: false
      name: Ethernet1/4
    - enabled: false
      name: Ethernet1/5
    - enabled: false
      name: Ethernet1/6
    - enabled: false
      name: Ethernet1/7
  enable:
    - enabled: true
      name: Ethernet1/4
    - enabled: true
      name: Ethernet1/5
    - enabled: true
      name: Ethernet1/6
    - enabled: true
      name: Ethernet1/7
  loopback:
    delete:
      - name: Loopback1
    create:
      - enabled: true
        name: Loopback1
    l3_members:
      - name: Loopback1
        ipv4:
          - address: 100.66.1.240/32
          - address: 100.66.1.234/32
            secondary: true
    ospf_members:
      - name: Loopback1
        address_family:
          - afi: ipv4
            processes:
              - process_id: 100
                area:
                  area_id: 0.0.0.0
    pim_interfaces:
      - interface: Loopback1
        hello_interval: 250
        hello_interval_ms: true
        sparse: true
l3:
  ospf_members:
    - name: Loopback1
      address_family:
        - afi: ipv4
          processes:
            - process_id: 100
              area:
                area_id: 0.0.0.0
    - name: Ethernet1/4
      address_family:
        - afi: ipv4
          authentication:
            enable: true
            message_digest: true
          authentication_key:
            encryption: 0
            key: ospf
          network: point-to-point
          processes:
            - process_id: 100
              area:
                area_id: 0.0.0.0
    - name: Ethernet1/5
      address_family:
        - afi: ipv4
          authentication:
            enable: true
            message_digest: true
          authentication_key:
            encryption: 0
            key: ospf
          network: point-to-point
          processes:
            - process_id: 100
              area:
                area_id: 0.0.0.0
    - name: Vlan3301
      address_family:
        - afi: ipv4
          authentication:
            enable: true
            message_digest: true
          authentication_key:
            encryption: 0
            key: ospf
          network: point-to-point
          processes:
            - process_id: 100
              area:
                area_id: 0.0.0.0
  l3_members:
    - name: Loopback1
      ipv4:
        - address: 100.66.1.240/32
        - address: 100.66.1.234/32
          secondary: true
    - name: Ethernet1/4
      ipv4:
        - address: 100.66.0.119/31
    - name: Ethernet1/5
      ipv4:
        - address: 100.66.0.123/31
    - name: Vlan3301
      ipv4:
        - address: 100.66.0.35/31
  members:
    - enabled: true
      name: Loopback1
    - enabled: true
      mtu: 9216
      mode: layer3
      name: Ethernet1/4
    - enabled: true
      mtu: 9216
      mode: layer3
      name: Ethernet1/5
    - enabled: true
      mtu: 9216
      name: Vlan3301
  pim_interfaces:
    - interface: Loopback1
      hello_interval: 250
      hello_interval_ms: true
      sparse: true
    - hello_interval: 250
      hello_interval_ms: true
      sparse: true
      interface: Ethernet1/4
    - hello_interval: 250
      hello_interval_ms: true
      sparse: true
      interface: Ethernet1/5
    - hello_interval: 250
      hello_interval_ms: true
      sparse: true
      interface: Vlan3301
  bgp_templates:
    as_number: 65000
    neighbor:
      - name: NOC_UNDERLAY-CPE-IBGP
        update_source: Loopback1
        address_family:
          - afi: ipv4
            safi: unicast
            send_community: both
            soft_reconfiguration_inbound:
              set: true
              always: true
          - afi: l2vpn
            safi: evpn
            send_community: both
  bgp:
    as_number: 65000
    log_neighbor_changes: true
    router_id: 100.66.1.240
    neighbors:
      - neighbor_address: 100.66.1.241
        remote_as: 65000
        password:
          encryption: 0
          key: bgp
        inherit:
          peer: NOC_UNDERLAY-CPE-IBGP
      - neighbor_address: 100.66.1.245
        remote_as: 65000
        password:
          encryption: 0
          key: bgp
        inherit:
          peer: NOC_UNDERLAY-CPE-IBGP
      - neighbor_address: 100.66.1.244
        remote_as: 65000
        password:
          encryption: 0
          key: bgp
        inherit:
          peer: NOC_UNDERLAY-CPE-IBGP
      - neighbor_address: 100.66.1.243
        remote_as: 65000
        password:
          encryption: 0
          key: bgp
        inherit:
          peer: NOC_UNDERLAY-CPE-IBGP
      - neighbor_address: 100.66.1.242
        remote_as: 65000
        password:
          encryption: 0
          key: bgp
        inherit:
          peer: NOC_UNDERLAY-CPE-IBGP
                
ospf:
  processes:
    - process_id: 100
      router_id: 100.66.1.240
      areas: 
        - area_id: 0.0.0.0
          authentication:
            message_digest: true
            set: true
      auto_cost:
        reference_bandwidth: 10
        unit: Gbps
      bfd: true
      log_adjacency_changes:
        log: true