ansible_host: 10.190.20.11
vpc_device:
  pkl_dest: 10.190.20.10
  pkl_src: 10.190.20.11
  role_priority: 32768

lab:
  disable:
    - enabled: false
      name: Ethernet1/1
    - enabled: false
      name: Ethernet1/2
    - enabled: false
      name: Ethernet1/3
    - enabled: false
      name: Ethernet1/4
    - enabled: false
      name: Ethernet1/5
    - enabled: false
      name: Ethernet1/6
    - enabled: false
      name: Ethernet1/7
  enable:
    - enabled: true
      name: Ethernet1/1
    - enabled: true
      name: Ethernet1/2
    - enabled: true
      name: Ethernet1/3
    - enabled: true
      name: Ethernet1/4
    - enabled: true
      name: Ethernet1/5
    - enabled: true
      name: Ethernet1/6
    - enabled: true
      name: Ethernet1/7

l3:
  ospf_members:
    - name: Loopback1
      address_family:
        - afi: ipv4
          processes:
            - process_id: 100
              area:
                area_id: 0.0.0.0
    - name: Loopback2
      address_family:
        - afi: ipv4
          network: point-to-point
          processes:
            - process_id: 100
              area:
                area_id: 0.0.0.0
    - name: Ethernet1/1
      address_family:
        - afi: ipv4
          authentication:
            enable: true
            message_digest: true
          authentication_key:
            encryption: 0
            key: ospf
          network: point-to-point
          processes:
            - process_id: 100
              area:
                area_id: 0.0.0.0
    - name: Ethernet1/3
      address_family:
        - afi: ipv4
          authentication:
            enable: true
            message_digest: true
          authentication_key:
            encryption: 0
            key: ospf
          network: point-to-point
          processes:
            - process_id: 100
              area:
                area_id: 0.0.0.0
    - name: Ethernet1/2
      address_family:
        - afi: ipv4
          authentication:
            enable: true
            message_digest: true
          authentication_key:
            encryption: 0
            key: ospf
          network: point-to-point
          processes:
            - process_id: 100
              area:
                area_id: 0.0.0.0
    - name: Ethernet1/4
      address_family:
        - afi: ipv4
          authentication:
            enable: true
            message_digest: true
          authentication_key:
            encryption: 0
            key: ospf
          network: point-to-point
          processes:
            - process_id: 100
              area:
                area_id: 0.0.0.0
    - name: Ethernet1/5
      address_family:
        - afi: ipv4
          authentication:
            enable: true
            message_digest: true
          authentication_key:
            encryption: 0
            key: ospf
          network: point-to-point
          processes:
            - process_id: 100
              area:
                area_id: 0.0.0.0
    - name: Vlan3200
      address_family:
        - afi: ipv4
          authentication:
            enable: true
            message_digest: true
          authentication_key:
            encryption: 0
            key: ospf
          network: point-to-point
          processes:
            - process_id: 100
              area:
                area_id: 0.0.0.0
  l3_members:
    - name: Loopback1
      ipv4:
        - address: 100.66.1.252/32
        - address: 100.66.1.237/32
          secondary: true
    - name: Loopback2
      ipv4:
        - address: 100.66.2.1/27
    - name: Ethernet1/1
      ipv4:
        - address: 100.66.0.9/31
    - name: Ethernet1/3
      ipv4:
        - address: 100.66.0.18/31
    - name: Ethernet1/2
      ipv4:
        - address: 100.66.0.5/31
    - name: Ethernet1/4
      ipv4:
        - address: 100.66.0.112/31
    - name: Ethernet1/5
      ipv4:
        - address: 100.66.0.114/31
    - name: Vlan3200
      ipv4:
        - address: 100.66.0.15/31
  members:
    - enabled: true
      name: Loopback1
    - enabled: true
      name: Loopback2
    - enabled: true
      mtu: 9216
      mode: layer3
      name: Ethernet1/1
    - enabled: true
      mtu: 9216
      mode: layer3
      name: Ethernet1/3
    - enabled: true
      mtu: 9216
      mode: layer3
      name: Ethernet1/2
    - enabled: true
      mtu: 9216
      mode: layer3
      name: Ethernet1/4
    - enabled: true
      mtu: 9216
      mode: layer3
      name: Ethernet1/5
    - enabled: true
      mtu: 9216
      name: Vlan3200
  pim_interfaces:
    - interface: Loopback1
      hello_interval: 250
      hello_interval_ms: true
      sparse: true
    - interface: Loopback2
      hello_interval: 250
      hello_interval_ms: true
      sparse: true
    - hello_interval: 250
      hello_interval_ms: true
      sparse: true
      interface: Ethernet1/1
    - hello_interval: 250
      hello_interval_ms: true
      sparse: true
      interface: Ethernet1/3
    - hello_interval: 250
      hello_interval_ms: true
      sparse: true
      interface: Ethernet1/2
    - hello_interval: 250
      hello_interval_ms: true
      sparse: true
      interface: Ethernet1/4
    - hello_interval: 250
      hello_interval_ms: true
      sparse: true
      interface: Ethernet1/5
    - hello_interval: 250
      hello_interval_ms: true
      sparse: true
      interface: Vlan3200
                
ospf:
  processes:
    - process_id: 100
      vrfs:
        - vrf: NOC_UNDERLAY
          router_id: 100.66.1.252
          areas: 
            - area_id: 0.0.0.0
              authentication:
                message_digest: true
                set: true
          auto_cost:
            reference_bandwidth: 10
            unit: Gbps
          bfd: true
          log_adjacency_changes:
            log: true