ansible_host: 10.190.10.10
vpc_device:
  pkl_dest: 10.190.10.11
  pkl_src: 10.190.10.10
  role_priority: 256

l3:
  members:
    - enabled: true
      mtu: 1500
      mode: layer3
      name: Loopback1
      ipv4:
        - address: 100.66.1.255/32
    - enabled: true
      mtu: 9216
      mode: layer3
      name: Ethernet1/1
      ipv4:
        - address: 100.66.0.2/31
    - enabled: true
      mtu: 9216
      mode: layer3
      name: Vlan3000
      ipv4:
        - address: 100.66.0.0/31